List<Map<String,dynamic>> places = [
  {
    "id"  : 1,
    "name":"Germany",
    "image1":"assets/assignment11/germany/germany1.jpg",
    "image2":"assets/assignment11/germany/germany2.jpg",
    "place1":"assets/assignment11/germany/g1.jpg",
    "place2":"assets/assignment11/germany/g2.jpg",
    "place3":"assets/assignment11/germany/g3.jpg",
    "place4":"assets/assignment11/germany/g4.jpg",
    "place5":"assets/assignment11/germany/g5.jpg",
    "place0":"assets/assignment11/germany/g6.jpg",
    "description": "Germany,[e] officially the Federal Republic of Germany,[f] is a country in Central Europe. It is the second-most populous country in Europe after Russia, and the most populous member state of the European Union."
  },
  {
    "id"  : 2,
    "name":"Italy",
    "image1":"assets/assignment11/italy/italy1.jpg",
    "image2":"assets/assignment11/italy/italy2.jpg",
    "place1":"assets/assignment11/italy/i1.jpg",
    "place2":"assets/assignment11/italy/i2.jpg",
    "place3":"assets/assignment11/italy/i3.jpg",
    "place4":"assets/assignment11/italy/i4.jpg",
    "place5":"assets/assignment11/italy/i5.jpg",
    "place0":"assets/assignment11/italy/i6.jpg",
    "description": "Italy (Italian: Italia [iˈtaːlja] (listen)), officially the Italian Republic[a][12][13] or the Republic of Italy,[14][15] is a country in Southern[16][17][18] and Western[19][note 1] Europe. Located in the middle of the Mediterranean Sea, it consists of a peninsula delimited by the Alps and surrounded by several islands.[20] Italy shares land borders with France, Switzerland, Austria, Slovenia and the enclaved microstates of Vatican City and San Marino. "
  },
  {
    "id"  : 3,
    "name":"Spain",
    "image1":"assets/assignment11/spain/spain1.jpg",
    "image2":"assets/assignment11/spain/spain2.jpg",
    "place1":"assets/assignment11/spain/s1.jpg",
    "place2":"assets/assignment11/spain/s2.jpg",
    "place3":"assets/assignment11/spain/s3.jpg",
    "place4":"assets/assignment11/spain/s4.jpg",
    "place5":"assets/assignment11/spain/s5.jpg",
    "place0":"assets/assignment11/spain/s6.jpg",
    "description": "Spain (Spanish: España, [esˈpaɲa] (listen)), or the Kingdom of Spain (Reino de España),[f] is a country located in Southwestern Europe, with parts of its territory in the Atlantic Ocean and across the Mediterranean Sea."
  },
  {
    "id"  : 4,
    "name":"India",
    "image1":"assets/assignment11/india/india1.jpg",
    "image2":"assets/assignment11/india/india2.jpg",
    "place1":"assets/assignment11/india/ind1.jpg",
    "place2":"assets/assignment11/india/ind2.jpg",
    "place3":"assets/assignment11/india/ind3.jpg",
    "place4":"assets/assignment11/india/ind4.jpg",
    "place5":"assets/assignment11/india/ind5.jpg",
    "place0":"assets/assignment11/india/ind6.jpg",
    "description": "India, officially the Republic of India (ISO: Bhārat Gaṇarājya),[22] is a country in South Asia. It is the seventh-largest country by area; the most populous country as of June 2023;[23][24] and from the time of its independence in 1947, the world's most populous democracy."},
  {
    "id"  : 5,
    "name":"UAE",
    "image1":"assets/assignment11/uae/uae1.jpg",
    "image2":"assets/assignment11/uae/uae2.jpg",
    "place1":"assets/assignment11/uae/uae1.jpg",
    "place2":"assets/assignment11/uae/u1.jpg",
    "place3":"assets/assignment11/uae/u2.jpg",
    "place4":"assets/assignment11/uae/u3.jpg",
    "place5":"assets/assignment11/uae/u4.jpg",
    "place0":"assets/assignment11/uae/u5.jpg",
    "description": "The United Arab Emirates (UAE; Arabic: الإمارات العربية المتحدة al-ʾImārāt al-ʿArabiyya l-Muttaḥida[note 2]), or simply the Emirates (Arabic: الإمارات al-ʾImārāt), is a country in West Asia, in the Middle East. It is located at the eastern end of the Arabian Peninsula and shares borders with Oman and Saudi Arabia"
  },
];